### ISSUE TITLE
Crash with java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by lovetomatoo** [tbruyelle/RxPermissions#125]
Log:
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                                                                         at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1413)
                                                                         at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1431)
                                                                         at android.app.BackStackRecord.commitInternal(BackStackRecord.java:693)
                                                                         at android.app.BackStackRecord.commit(BackStackRecord.java:669)
                                                                         at com.tbruyelle.rxpermissions.RxPermissions.getRxPermissionsFragment(RxPermissions.java:50)
                                                                         at com.tbruyelle.rxpermissions.RxPermissions.<init>(RxPermissions.java:38)
                                                                         at com.maimiao.live.game.ui.activity.SplashActivity.toPushSetting(SplashActivity.java:111)
                                                                         at com.maimiao.live.game.presenter.SplashPresenter.lambda$delayStartAct$0(SplashPresenter.java:72)
                                                                         at com.maimiao.live.game.presenter.SplashPresenter.access$lambda$0(SplashPresenter.java:0)
                                                                         at com.maimiao.live.game.presenter.SplashPresenter$$Lambda$1.run(Unknown Source)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

    crash in my splash activity ,i'm press home key when i start splashactivity...eeee  sometimes  boooom
    i guess because this method: getRxPermissionsFragment() used fragmentManager.commit but not commitAllowingStateLoss(). but i'm can't resolve it, because the methed is private.
   help!!!!!!!

**Comment by tbruyelle** [comment]
Ow I think there's a PR for that... #121

**Comment by tbruyelle** [comment]
You probably do something wrong with your fragment usage to have this exception, anyway, version 0.9.2 now perform `commitAllowingStateLoss`.

**Comment by lovetomatoo** [comment]
I use 0.9.1, so the problem occurred.Upgrade now. thank you !!

**Comment by thirtyyuan** [comment]
Why perform 'commitNow()' again at version 0.10.2 ? And how can I fix it?

**Comment by lovetomatoo** [comment]
@thirtyyuan 你可以不用这个版本，虽然这不是一个很好的方案。

**Comment by RangerAnan** [comment]
刚升级到0.10.2，然而又要降下去。。。

**Comment by andansky** [comment]
Why perform 'commitNow()' again at version 0.10.2 ? And how can I fix it?

**Comment by yyzl0418** [comment]
version 0.12
java.lang.IllegalStateException
Can not perform this action after onSaveInstanceState
com.tbruyelle.rxpermissions3.RxPermissions.getRxPermissionsFragment(RxPermissions.java:78)

**Comment by yyzl0418** [comment]
@tbruyelle 
version 0.12
java.lang.IllegalStateException
Can not perform this action after onSaveInstanceState
com.tbruyelle.rxpermissions3.RxPermissions.getRxPermissionsFragment(RxPermissions.java:78)
