### ISSUE TITLE
IllegalStateExceptionRecursive entry to executePendingTransactions

### ISSUE THREAD

**Issue by priyakar** [tbruyelle/RxPermissions#155]
I have permissions in BaseActivity and my BaseFragment is calling that method but I keep getting a weird crash when I get to the fragment that is calling the BaseFragment method for permissions.

FATAL EXCEPTION: main
                                                                Process: packagename, PID: 27295
                                                                java.lang.IllegalStateException: Recursive entry to executePendingTransactions
                                                                    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1550)
                                                                    at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:563)
                                                                    at com.tbruyelle.rxpermissions2.RxPermissions.getRxPermissionsFragment(RxPermissions.java:54)
                                                                    at com.tbruyelle.rxpermissions2.RxPermissions.<init>(RxPermissions.java:41)
                                                                    at packagename.BaseFragment.requestPermissions(BaseFragment.kt:123)
                                                                    at packagename.SomeFragment.method(SomeFragment.kt:86)
                                                                    at packagename.SomePresenter.method(SomePresenter.kt:53)
                                                                    at packagename.FragmentPresenter.onCreate$app(FragmentPresenter.kt:15)
                                                                    at packagename.BaseFragment.onCreate(BaseFragment.kt:62)
                                                                    at android.app.Fragment.performCreate(Fragment.java:2344)
                                                                    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:949)
                                                                    at android.app.BackStackRecord.setLastIn(BackStackRecord.java:857)
                                                                    at android.app.BackStackRecord.calculateFragments(BackStackRecord.java:897)
                                                                    at android.app.BackStackRecord.run(BackStackRecord.java:727)
                                                                    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1582)
                                                                    at android.app.FragmentManagerImpl$1.run(FragmentManager.java:483)
                                                                    at android.os.Handler.handleCallback(Handler.java:751)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6310)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

**Comment by trueangle** [comment]
Same problem, when I create new RxPermissions instance in fragment. This is  because android doesn't allow to call one fragment from another within the same FragmentManager. We need to use fragment.getChildFragmentManager() instead of activity.getFragmentManager() if we want to create RxPermissions instance from fragment.

**Comment by Walker-ZHAO** [comment]
Same error.
I use TabLayout and ViewPager.  This is my code:

**Comment by scm573** [comment]
I'm facing the same trouble. And as @trueangle said, I tried to modify the RxPermissions class:
```java
    public RxPermissions(@NonNull Fragment fragment) {
        mRxPermissionsFragment = getRxPermissionsFragment(fragment);
    }

    private RxPermissionsFragment getRxPermissionsFragment(Fragment fragment) {
        RxPermissionsFragment rxPermissionsFragment = findRxPermissionsFragment(fragment);
        boolean isNewInstance = rxPermissionsFragment == null;
        if (isNewInstance) {
            rxPermissionsFragment = new RxPermissionsFragment();
            FragmentManager fragmentManager = fragment.getChildFragmentManager();
            fragmentManager
                    .beginTransaction()
                    .add(rxPermissionsFragment, TAG)
                    .commitAllowingStateLoss();
            fragmentManager.executePendingTransactions();
        }
        return rxPermissionsFragment;
    }

    private RxPermissionsFragment findRxPermissionsFragment(Fragment fragment) {
        return (RxPermissionsFragment) fragment.getChildFragmentManager().findFragmentByTag(TAG);
    }
```
And it works like a charm. However getChildFragmentManager() isn't supported before API 17, also I'm not sure whether this handling meets your expectations.
If you could accept this or provide any better solutions, it'll be great appreciated since I really need it in my project.

Best,

**Comment by a1018875550** [comment]
it's not in the library?

**Comment by scm573** [comment]
@a1018875550 

You mean the block I pasted above? No. There're actually some other problems need to be handled. I cannot assure that everything would work well. If you need that you may take a look at my fork or make your own.

**Comment by a1018875550** [comment]
thank's ,okay..
