### ISSUE TITLE
Fatal Exception : unable resume activity

### ISSUE THREAD

**Issue by pratamawijaya** [tbruyelle/RxPermissions#16]
i have trying implement in my apps, but its error and here are the logcat (Nexus 6 - Android 6.0)

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {kulina.id/com.tbruyelle.rxpermissions.ShadowActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=42, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {kulina.id/com.tbruyelle.rxpermissions.ShadowActivity}: java.lang.IllegalStateException: RxPermissions.onRequestPermissionsResult invoked but didn't find the corresponding permission request.
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
       at android.os.Handler.dispatchMessage(Handler.java)
       at android.os.Looper.loop(Looper.java)
       at android.app.ActivityThread.main(ActivityThread.java)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
Caused by java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=42, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {kulina.id/com.tbruyelle.rxpermissions.ShadowActivity}: java.lang.IllegalStateException: RxPermissions.onRequestPermissionsResult invoked but didn't find the corresponding permission request.
       at android.app.ActivityThread.deliverResults(ActivityThread.java)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
       at android.os.Handler.dispatchMessage(Handler.java)
       at android.os.Looper.loop(Looper.java)
       at android.app.ActivityThread.main(ActivityThread.java)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
Caused by java.lang.IllegalStateException: RxPermissions.onRequestPermissionsResult invoked but didn't find the corresponding permission request.
       at com.tbruyelle.rxpermissions.RxPermissions.onRequestPermissionsResult(RxPermissions.java)
       at com.tbruyelle.rxpermissions.ShadowActivity.onRequestPermissionsResult(ShadowActivity.java)
       at android.app.Activity.dispatchRequestPermissionsResult(Activity.java)
       at android.app.Activity.dispatchActivityResult(Activity.java)
       at android.app.ActivityThread.deliverResults(ActivityThread.java)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
       at android.os.Handler.dispatchMessage(Handler.java)
       at android.os.Looper.loop(Looper.java)
       at android.app.ActivityThread.main(ActivityThread.java)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)

```

and here are my code
```
if (Build.VERSION.SDK_INT >= 23) {
      RxPermissions.getInstance(this)
          .request(Manifest.permission.INTERNET, Manifest.permission.ACCESS_NETWORK_STATE,
              Manifest.permission.WAKE_LOCK, Manifest.permission.WRITE_EXTERNAL_STORAGE,
              Manifest.permission.GET_ACCOUNTS, Manifest.permission.RECEIVE_SMS,
              Manifest.permission.READ_SMS, Manifest.permission.READ_CONTACTS,
              Manifest.permission.READ_LOGS, Manifest.permission.ACCESS_COARSE_LOCATION,
              Manifest.permission.RECORD_AUDIO, Manifest.permission.MODIFY_AUDIO_SETTINGS,
              Manifest.permission.READ_PHONE_STATE, Manifest.permission.SYSTEM_ALERT_WINDOW)
          .subscribe(granted -> {
            if (granted) {
              // do something
            } else {
              Toast.makeText(SplashActivity.this, "some permission denied by user",
                  Toast.LENGTH_SHORT).show();
            }
          });
    } else {
     // do something
    }
```

**Comment by tbruyelle** [comment]
ok, first you don't need to check the sdk version, it's handled by the library. If `Build.VERSION.SDK_INT < 23`, the observer will immediately receive a granted result.

Secondly, it seems you're not well informed about runtime permissions. Only a  part of the permissions requires a request : the dangerous ones, as Google names them [1]. 

About the crash itself, I think it's exactly because you request permissions that don't need to be requested. Try to filter the parameter list with only *dangerous* permissions and it should work.

That said you pointed a weakness in the library that needs a fix. Thanks !

[1] https://developer.android.com/guide/topics/security/permissions.html#normal-dangerous

**Comment by tbruyelle** [comment]
After some tests, there is finally no issue in requesting non-dangerous permissions, but the framework will always answer the permission is not granted. The answer is propagated without change by the library.

Could you tell me if you still have the issue with the last version of `RxPermissions` ?

**Comment by tbruyelle** [comment]
Closed for no activity

**Comment by hanibalsk** [comment]
I had same this error today in Craslytics(lg_h815 - Android 6.0):
Fatal Exception: java.lang.RuntimeException
Failure delivering result ResultInfo{who=@android:requestPermissions:, request=42, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {sk.bonbon.kosiceregion/com.tbruyelle.rxpermissions.ShadowActivity}: java.lang.IllegalStateException: RxPermissions.onRequestPermissionsResult invoked but didn't find the corresponding permission request.
 Raw
android.app.ActivityThread.deliverResults (ActivityThread.java:3742)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:620)

Caused by java.lang.IllegalStateException
com.tbruyelle.rxpermissions.RxPermissions.onRequestPermissionsResult (RxPermissions.java:286)
com.tbruyelle.rxpermissions.ShadowActivity.onRequestPermissionsResult (ShadowActivity.java:32)
android.app.Activity.dispatchRequestPermissionsResult (Activity.java:6588)
android.app.Activity.dispatchActivityResult (Activity.java:6467)
android.app.ActivityThread.deliverResults (ActivityThread.java:3738)
android.app.ActivityThread.handleSendResult (ActivityThread.java:3785)
android.app.ActivityThread.access$1400 (ActivityThread.java:157)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1405)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:5525)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:730)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:620)`

**Comment by VitalyKolchenko** [comment]
+1 Same error on Samsyng galaxy edge 7 in crashlytics 

Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.bound360.temed.patient/com.tbruyelle.rxpermissions.ShadowActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=42, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS VirtualScreenParam=Params{mDisplayId=-1, null, mFlags=0x00000000)} (has extras) }} to activity {com.bound360.temed.patient/com.tbruyelle.rxpermissions.ShadowActivity}: java.lang.IllegalStateException: RxPermissions.onRequestPermissionsResult invoked but didn't find the corresponding permission request.
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4156)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4250)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3361)
       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=42, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS VirtualScreenParam=Params{mDisplayId=-1, null, mFlags=0x00000000)} (has extras) }} to activity {com.bound360.temed.patient/com.tbruyelle.rxpermissions.ShadowActivity}: java.lang.IllegalStateException: RxPermissions.onRequestPermissionsResult invoked but didn't find the corresponding permission request.
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4925)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4142)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4250)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3361)
       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by java.lang.IllegalStateException: RxPermissions.onRequestPermissionsResult invoked but didn't find the corresponding permission request.
       at com.tbruyelle.rxpermissions.RxPermissions.onRequestPermissionsResult(RxPermissions.java:286)
       at com.tbruyelle.rxpermissions.ShadowActivity.onRequestPermissionsResult(ShadowActivity.java:32)
       at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7263)
       at android.app.Activity.dispatchActivityResult(Activity.java:7141)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4921)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4142)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4250)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3361)
       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
