### ISSUE TITLE
点击打开相机的时候偶尔会出现

### ISSUE THREAD

**Issue by yuzhongrong** [tbruyelle/RxPermissions#174]
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.app.Activity.checkSelfPermission(java.lang.String)' on a null object reference
                                                                      at com.tbruyelle.rxpermissions.RxPermissionsFragment.isGranted(RxPermissionsFragment.java:73)
                                                                      at com.tbruyelle.rxpermissions.RxPermissions.isGranted(RxPermissions.java:248)
                                                                      at com.tbruyelle.rxpermissions.RxPermissions.requestImplementation(RxPermissions.java:174)
                                                                      at com.tbruyelle.rxpermissions.RxPermissions.access$100(RxPermissions.java:31)
                                                                      at com.tbruyelle.rxpermissions.RxPermissions$3.call(RxPermissions.java:144)
                                                                      at com.tbruyelle.rxpermissions.RxPermissions$3.call(RxPermissions.java:141)
                                                                      at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:66)
                                                                      	... 36 more
                                                                   Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: null
                                                                      at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:70)
                                                                      	... 36 more

**Comment by yuzhongrong** [comment]
什么情况

**Comment by yuzhongrong** [comment]
问题比较紧急请告知什么问题 我是在一个activitie中弹一个popwindow 选择相册相机等 点击相机item时候挂了 10次有5到6次是这样

**Comment by yuzhongrong** [comment]
抱错上说我的activiti 为空 可是我的activitie上下文是传到popwindow 的

**Comment by tbruyelle** [comment]
Speak english please

**Comment by sfyc23** [comment]
RxPermissions rxPermissions = new RxPermissions(this); // where this is an Activity instance
这个意思是，初始化时，要传入 Activity 对象。

**Comment by hhecoder** [comment]
sorry for his Chinese question.
