### ISSUE TITLE
 Multiple dex files define Lcom/tbruyelle/rxpermissions/BuildConfig

### ISSUE THREAD

**Issue by classTC** [tbruyelle/RxPermissions#176]
When I upgrade to RxJava2 and RxPermissions2，I got this error (have done every steps as README said)

below is error messages
```
Execution failed for task ':app:transformDexArchiveWithDexMergerForStageDebug'.
> com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lcom/tbruyelle/rxpermissions/BuildConfig;

```
```
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/tbruyelle/rxpermissions/BuildConfig;
Error:	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
Error:	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
Error:	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
Error:	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Error:	at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
Error:	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
Error:	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
Error:	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Error:	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
Error:	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by classTC** [comment]
Fix it...
because I have another module used the old version...
just upgrade and clean project

**Comment by iffanmajid** [comment]
I have same issue, already clean it up, but no luck.
