### ISSUE TITLE
有些手机申请权限出错, 导致崩溃

### ISSUE THREAD

**Issue by badboy-tian** [tbruyelle/RxPermissions#202]
```
io.reactivex.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'int android.app.Activity.checkSelfPermission(java.lang.String)' on a null object reference
at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:74)
at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.checkTerminate(ObservableFlatMap.java:495)
at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drainLoop(ObservableFlatMap.java:331)
at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drain(ObservableFlatMap.java:323)
at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onError(ObservableFlatMap.java:288)
at io.reactivex.internal.operators.observable.ObservableBuffer$BufferExactObserver.onError(ObservableBuffer.java:124)
at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.checkTerminate(ObservableFlatMap.java:495)
at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drainLoop(ObservableFlatMap.java:331)
at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drain(ObservableFlatMap.java:323)
at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onError(ObservableFlatMap.java:288)
at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:125)
at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.tryEmitScalar(ObservableFlatMap.java:234)
at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:146)
at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:139)
at io.reactivex.internal.operators.observable.ObservableFromArray$FromArrayDisposable.run(ObservableFromArray.java:107)
at io.reactivex.internal.operators.observable.ObservableFromArray.subscribeActual(ObservableFromArray.java:36)
at io.reactivex.Observable.subscribe(Observable.java:10903)
at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
at io.reactivex.Observable.subscribe(Observable.java:10903)
at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
at io.reactivex.Observable.subscribe(Observable.java:10903)
at io.reactivex.internal.operators.observable.ObservableBuffer.subscribeActual(ObservableBuffer.java:44)
at io.reactivex.Observable.subscribe(Observable.java:10903)
at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
at io.reactivex.Observable.subscribe(Observable.java:10903)
at io.reactivex.Observable.subscribe(Observable.java:10889)
at io.reactivex.Observable.subscribe(Observable.java:10792)
at com.i7play.rts.activity.SplashActivity.showMainActivity(SplashActivity.kt:187)
at com.i7play.rts.activity.SplashActivity.showMainActivity(SplashActivity.kt:179)
at com.i7play.rts.activity.SplashActivity.onIntent(SplashActivity.kt:146)
at com.i7play.rts.activity.SplashActivity.access$onIntent(SplashActivity.kt:31)
at com.i7play.rts.activity.SplashActivity$onResume$runnable$1.run(SplashActivity.kt:65)
at android.os.Handler.handleCallback(Handler.java:808)
at android.os.Handler.dispatchMessage(Handler.java:101)
at android.os.Looper.loop(Looper.java:166)
at android.app.ActivityThread.main(ActivityThread.java:7406)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:926)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.app.Activity.checkSelfPermission(java.lang.String)' on a null object reference
at com.tbruyelle.rxpermissions2.RxPermissionsFragment.isGranted(RxPermissionsFragment.java:71)
at com.tbruyelle.rxpermissions2.RxPermissions.isGranted(RxPermissions.java:251)
at com.tbruyelle.rxpermissions2.RxPermissions.requestImplementation(RxPermissions.java:177)
at com.tbruyelle.rxpermissions2.RxPermissions.access$100(RxPermissions.java:33)
at com.tbruyelle.rxpermissions2.RxPermissions$3.apply(RxPermissions.java:147)
at com.tbruyelle.rxpermissions2.RxPermissions$3.apply(RxPermissions.java:144)
at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:121)
... 28 more
```

**Comment by BradyXuBin** [comment]
我也出现这个问题，请问有什么解决办法嘛？

**Comment by amsterly** [comment]
百度一下

**Comment by zhangle1024** [comment]
猜测应该是调用checkSelfPermission时，给了个null对象进去，期望是一个字符串。

**Comment by 317056658** [comment]
看你们的回答 我感觉 还是用原生最可靠了。

**Comment by zhangle1024** [comment]
> 看你们的回答 我感觉 还是用原生最可靠了。

框架底层大部分都是基于原生的封装的，只不过优秀的框架可以明确的告诉你错在什么地方了。同样你用原生的也可以，但是自己写的不一定有人家好！

**Comment by 317056658** [comment]
> > 看你们的回答 我感觉 还是用原生最可靠了。
> 
> 框架底层大部分都是基于原生的封装的，只不过优秀的框架可以明确的告诉你错在什么地方了。同样你用原生的也可以，但是自己写的不一定有人家好！这个库自带Rxjava2

**Comment by 317056658** [comment]
> > 看你们的回答 我感觉 还是用原生最可靠了。
> 
> 框架底层大部分都是基于原生的封装的，只不过优秀的框架可以明确的告诉你错在什么地方了。同样你用原生的也可以，但是自己写的不一定有人家好！

这个库自带rxjava2   如果自己也引用rxjava2 不会造成资源浪费吗？

**Comment by kamaelyoung** [comment]
> > > 看你们的回答 我感觉 还是用原生最可靠了。
> > 
> > 
> > 框架底层大部分都是基于原生的封装的，只不过优秀的框架可以明确的告诉你错在什么地方了。同样你用原生的也可以，但是自己写的不一定有人家好！
> 
> 这个库自带rxjava2 如果自己也引用rxjava2 不会造成资源浪费吗？


  implementation ('rxpermissions'){
    exclude group: 'rxjava'
  }

**Comment by ladingwu** [comment]
OnErrorNotImplementedException,没有实现onError方法，导致错误无法传递

**Comment by tbruyelle** [comment]
Please write the issue in english.
