### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Myeongwon-Kang** [tbruyelle/RxPermissions#246]
i use lib version 0.10.2

I had a crash.

log.
java.lang.IllegalStateException: FragmentManager is already executing transactions
        at android.support.v4.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:2179)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2211)
        at android.support.v4.app.BackStackRecord.commitNow(BackStackRecord.java:643)
        at com.tbruyelle.rxpermissions2.RxPermissions.getRxPermissionsFragment(RxPermissions.java:77)
        at com.tbruyelle.rxpermissions2.RxPermissions.access$000(RxPermissions.java:36)
        at com.tbruyelle.rxpermissions2.RxPermissions$1.get(RxPermissions.java:61)
        at com.tbruyelle.rxpermissions2.RxPermissions$1.get(RxPermissions.java:54)
        at com.tbruyelle.rxpermissions2.RxPermissions.pending(RxPermissions.java:211)
        at com.tbruyelle.rxpermissions2.RxPermissions.request(RxPermissions.java:200)
        at com.tbruyelle.rxpermissions2.RxPermissions.access$100(RxPermissions.java:36)
        at com.tbruyelle.rxpermissions2.RxPermissions$2.apply(RxPermissions.java:102)
        at io.reactivex.Observable.compose(Observable.java:6337)
        at com.tbruyelle.rxpermissions2.RxPermissions.request(RxPermissions.java:176)

**Comment by pawegio** [comment]
Same here.

Nexus 5X
Android 8.1

**Comment by olegsvs** [comment]
same
