### ISSUE TITLE
error: duplicate value for resource 'attr/layout_anchorGravity' with config

### ISSUE THREAD

**Issue by dasbiswajit** [tbruyelle/RxPermissions#262]
Hello Team,
I am struggling to use this library. I follow the steps as given in [Setup](https://github.com/tbruyelle/RxPermissions#setup). But getting constantly the following error. I did clean the project, clear the cache and delete .gradle folder too did not help. Below is the console output.

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':WeAC:mergeDebugResources'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.internal.UncheckedException: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
Output:  /Users/biswajitdas/StudioProjects/weatheralarmclock/WeAC/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:10627: error: duplicate value for resource 'attr/layout_anchorGravity' with config ''.
/Users/biswajitdas/StudioProjects/weatheralarmclock/WeAC/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:10627: error: resource previously defined here.

Command: /Users/biswajitdas/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-osx.jar/822b3beac23de4fce7734d43d7ea2a38/aapt2-3.2.1-4818971-osx/aapt2 compile --legacy \
        -o \
        /Users/biswajitdas/StudioProjects/weatheralarmclock/WeAC/build/intermediates/res/merged/debug \
        /Users/biswajitdas/StudioProjects/weatheralarmclock/WeAC/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
Daemon:  AAPT2 aapt2-3.2.1-4818971-osx Daemon #2
Output:  /Users/biswajitdas/.gradle/caches/transforms-1/files-1.1/design-23.3.0.aar/54c12d20627b3156c3385009d89989e3/res/values/values.xml:19:5-827: AAPT: error: duplicate value for resource 'attr/layout_anchorGravity' with config ''.
    
/Users/biswajitdas/.gradle/caches/transforms-1/files-1.1/design-23.3.0.aar/54c12d20627b3156c3385009d89989e3/res/values/values.xml:19:5-827: AAPT: error: resource previously defined here.
    
Command: /Users/biswajitdas/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-osx.jar/822b3beac23de4fce7734d43d7ea2a38/aapt2-3.2.1-4818971-osx/aapt2 compile --legacy \
        -o \
        /Users/biswajitdas/StudioProjects/weatheralarmclock/WeAC/build/intermediates/res/merged/debug \
        /Users/biswajitdas/StudioProjects/weatheralarmclock/WeAC/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
Daemon:  AAPT2 aapt2-3.2.1-4818971-osx Daemon #2
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:63)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:76)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
	... 33 more
Caused by: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
Output:  /Users/biswajitdas/StudioProjects/weatheralarmclock/WeAC/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:10627: error: duplicate value for resource 'attr/layout_anchorGravity' with config ''.
/Users/biswajitdas/StudioProjects/weatheralarmclock/WeAC/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:10627: error: resource previously defined here.

Command: /Users/biswajitdas/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-osx.jar/822b3beac23de4fce7734d43d7ea2a38/aapt2-3.2.1-4818971-osx/aapt2 compile --legacy \
        -o \
        /Users/biswajitdas/StudioProjects/weatheralarmclock/WeAC/build/intermediates/res/merged/debug \
        /Users/biswajitdas/StudioProjects/weatheralarmclock/WeAC/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
Daemon:  AAPT2 aapt2-3.2.1-4818971-osx Daemon #2
Output:  /Users/biswajitdas/.gradle/caches/transforms-1/files-1.1/design-23.3.0.aar/54c12d20627b3156c3385009d89989e3/res/values/values.xml:19:5-827: AAPT: error: duplicate value for resource 'attr/layout_anchorGravity' with config ''.
    
/Users/biswajitdas/.gradle/caches/transforms-1/files-1.1/design-23.3.0.aar/54c12d20627b3156c3385009d89989e3/res/values/values.xml:19:5-827: AAPT: error: resource previously defined here.
    
Command: /Users/biswajitdas/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-osx.jar/822b3beac23de4fce7734d43d7ea2a38/aapt2-3.2.1-4818971-osx/aapt2 compile --legacy \
        -o \
        /Users/biswajitdas/StudioProjects/weatheralarmclock/WeAC/build/intermediates/res/merged/debug \
        /Users/biswajitdas/StudioProjects/weatheralarmclock/WeAC/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
Daemon:  AAPT2 aapt2-3.2.1-4818971-osx Daemon #2
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at com.android.ide.common.workers.ExecutorServiceAdapter.close(ExecutorServiceAdapter.kt:56)
	at com.android.build.gradle.internal.aapt.WorkerExecutorResourceCompilationService.close(WorkerExecutorResourceCompilationService.kt:67)
	at com.android.build.gradle.tasks.MergeResources.doFullTaskAction(MergeResources.java:324)
	at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	... 43 more
Caused by: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
Output:  /Users/biswajitdas/StudioProjects/weatheralarmclock/WeAC/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:10627: error: duplicate value for resource 'attr/layout_anchorGravity' with config ''.
/Users/biswajitdas/StudioProjects/weatheralarmclock/WeAC/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:10627: error: resource previously defined here.

Command: /Users/biswajitdas/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-osx.jar/822b3beac23de4fce7734d43d7ea2a38/aapt2-3.2.1-4818971-osx/aapt2 compile --legacy \
        -o \
        /Users/biswajitdas/StudioProjects/weatheralarmclock/WeAC/build/intermediates/res/merged/debug \
        /Users/biswajitdas/StudioProjects/weatheralarmclock/WeAC/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
Daemon:  AAPT2 aapt2-3.2.1-4818971-osx Daemon #2
Output:  /Users/biswajitdas/.gradle/caches/transforms-1/files-1.1/design-23.3.0.aar/54c12d20627b3156c3385009d89989e3/res/values/values.xml:19:5-827: AAPT: error: duplicate value for resource 'attr/layout_anchorGravity' with config ''.
    
/Users/biswajitdas/.gradle/caches/transforms-1/files-1.1/design-23.3.0.aar/54c12d20627b3156c3385009d89989e3/res/values/values.xml:19:5-827: AAPT: error: resource previously defined here.
    
Command: /Users/biswajitdas/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-osx.jar/822b3beac23de4fce7734d43d7ea2a38/aapt2-3.2.1-4818971-osx/aapt2 compile --legacy \
        -o \
        /Users/biswajitdas/StudioProjects/weatheralarmclock/WeAC/build/intermediates/res/merged/debug \
        /Users/biswajitdas/StudioProjects/weatheralarmclock/WeAC/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
Daemon:  AAPT2 aapt2-3.2.1-4818971-osx Daemon #2
	at com.android.build.gradle.internal.res.Aapt2ErrorUtils.rewriteException(Aapt2ErrorUtils.kt:97)
	at com.android.build.gradle.internal.res.Aapt2ErrorUtils.rewriteCompileException(Aapt2ErrorUtils.kt:55)
	at com.android.build.gradle.internal.res.Aapt2CompileWithBlameRunnable$run$1.invoke(Aapt2CompileWithBlameRunnable.kt:39)
	at com.android.build.gradle.internal.res.Aapt2CompileWithBlameRunnable$run$1.invoke(Aapt2CompileWithBlameRunnable.kt:28)
	at com.android.build.gradle.internal.res.namespaced.Aapt2DaemonManagerService.useAaptDaemon(Aapt2DaemonManagerService.kt:71)
	at com.android.build.gradle.internal.res.namespaced.Aapt2DaemonManagerService.useAaptDaemon$default(Aapt2DaemonManagerService.kt:69)
	at com.android.build.gradle.internal.res.Aapt2CompileWithBlameRunnable.run(Aapt2CompileWithBlameRunnable.kt:34)
	at com.android.ide.common.workers.ExecutorServiceAdapter$submit$submission$1.run(ExecutorServiceAdapter.kt:39)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
Output:  /Users/biswajitdas/StudioProjects/weatheralarmclock/WeAC/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:10627: error: duplicate value for resource 'attr/layout_anchorGravity' with config ''.
/Users/biswajitdas/StudioProjects/weatheralarmclock/WeAC/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:10627: error: resource previously defined here.

Command: /Users/biswajitdas/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-osx.jar/822b3beac23de4fce7734d43d7ea2a38/aapt2-3.2.1-4818971-osx/aapt2 compile --legacy \
        -o \
        /Users/biswajitdas/StudioProjects/weatheralarmclock/WeAC/build/intermediates/res/merged/debug \
        /Users/biswajitdas/StudioProjects/weatheralarmclock/WeAC/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
Daemon:  AAPT2 aapt2-3.2.1-4818971-osx Daemon #2
	at com.android.builder.internal.aapt.v2.Aapt2DaemonImpl.doCompile(Aapt2DaemonImpl.kt:142)
	at com.android.builder.internal.aapt.v2.Aapt2Daemon.compile(Aapt2Daemon.kt:81)
	at com.android.builder.internal.aapt.v2.Aapt2DaemonManager$LeasedAaptDaemon.compile(Aapt2DaemonManager.kt:170)
	at com.android.build.gradle.internal.res.Aapt2CompileWithBlameRunnable$run$1.invoke(Aapt2CompileWithBlameRunnable.kt:37)
	... 10 more

**Comment by dasbiswajit** [comment]
we fixed it by adding the line with Gradle file. Thanks @kaku2015
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '27.1.1'
            }
        }
    }
}
