### ISSUE TITLE
Failure delivering result ResultInfo{who=@android:requestPermissions:, request=42, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.vt.magicmotion/com.tbruyelle.rxpermissions.ShadowActivity}

### ISSUE THREAD

**Issue by XWindMan** [tbruyelle/RxPermissions#285]
Failure delivering result ResultInfo{who=@android:requestPermissions:, request=42, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.vt.magicmotion/com.tbruyelle.rxpermissions.ShadowActivity}

**Comment by wuhenzhizao** [comment]
碰到相同的问题
Caused by: java.lang.NullPointerException: Attempt to read from null array
	at com.c.a.c.a(RxPermissionsFragment.java:63)
	at com.c.a.c.onRequestPermissionsResult(RxPermissionsFragment.java:49)
	at android.app.Activity.dispatchRequestPermissionsResultToFragment(Activity.java:7638)
	at android.app.Activity.dispatchActivityResult(Activity.java:7482)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4462)
	... 11 more
