### ISSUE TITLE
java.lang.IllegalStateException: Fragment host has been destroyed

### ISSUE THREAD

**Issue by trycatchx** [tbruyelle/RxPermissions#286]
monkey Crash log，how to solve it, thx!
```
  java.lang.IllegalStateException: Fragment host has been destroyed
        at android.support.v4.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:2211)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2239)
        at android.support.v4.app.BackStackRecord.commitNow(BackStackRecord.java:648)
        at com.tbruyelle.rxpermissions2.RxPermissions.getRxPermissionsFragment(RxPermissions.java:71)
        at com.tbruyelle.rxpermissions2.RxPermissions.access$000(RxPermissions.java:34)
        at com.tbruyelle.rxpermissions2.RxPermissions$1.get(RxPermissions.java:54)
        at com.tbruyelle.rxpermissions2.RxPermissions$1.get(RxPermissions.java:47)
        at com.tbruyelle.rxpermissions2.RxPermissions.pending(RxPermissions.java:205)
        at com.tbruyelle.rxpermissions2.RxPermissions.request(RxPermissions.java:194)
        at com.tbruyelle.rxpermissions2.RxPermissions.access$100(RxPermissions.java:34)
        at com.tbruyelle.rxpermissions2.RxPermissions$2.apply(RxPermissions.java:96)
        at io.reactivex.Observable.compose(Observable.java:6418)
        at com.tbruyelle.rxpermissions2.RxPermissions.request(RxPermissions.java:170)
        at com.tct.toolscard.ToolsCardView.toggleFlashLight(ToolsCardView.java:152)
        at com.tct.toolscard.ToolsCardView.onClick(ToolsCardView.java:254)
        at android.view.View.performClick(View.java:6615)
        at android.view.View.performClickInternal(View.java:6592)
        at android.view.View.access$3100(View.java:786)
        at android.view.View$PerformClick.run(View.java:25951)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by foodied** [comment]
Subscribe/Unsubscribe inside lifecycle methods?

**Comment by zhangchaojiong** [comment]
I upgraded to V0.10.2 and solved it. @foodied

**Comment by JoyHong** [comment]
v0.10.2 still have this issue

**Comment by xingxiang1989** [comment]
i got this crash still on V0.10.2 , who has the method to fix this.

**Comment by Shirwee** [comment]
> i got this crash still on V0.10.2 , who has the method to fix this.

me too

**Comment by JoyHong** [comment]
me too

**Comment by hoanghiephui** [comment]
Thank

**Comment by robertchar** [comment]
me to

**Comment by will746** [comment]
me too

**Comment by nidhi88** [comment]
Me too

**Comment by jingmaolin** [comment]
Me too

**Comment by IliaKhuzhakhmetovRoonyx** [comment]
Me too

**Comment by XuEnhao** [comment]
Me too

**Comment by serdarbuyukkanli-exi** [comment]
Is there any update on that?
