### ISSUE TITLE
Failure delivering result ResultInfo

### ISSUE THREAD

**Issue by wuhenzhizao** [tbruyelle/RxPermissions#303]
10-16 11:13:00.060 13775 13775 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:android:fragment:1, request=42, result=0, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {.ui.activity.MainActivity}: java.lang.NullPointerException: Attempt to read from null array
10-16 11:13:00.060 13775 13775 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4469)
10-16 11:13:00.060 13775 13775 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4511)
10-16 11:13:00.060 13775 13775 E AndroidRuntime: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
10-16 11:13:00.060 13775 13775 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
10-16 11:13:00.060 13775 13775 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
10-16 11:13:00.060 13775 13775 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
10-16 11:13:00.060 13775 13775 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-16 11:13:00.060 13775 13775 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
10-16 11:13:00.060 13775 13775 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6874)
10-16 11:13:00.060 13775 13775 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-16 11:13:00.060 13775 13775 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-16 11:13:00.060 13775 13775 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:861)
10-16 11:13:00.060 13775 13775 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to read from null array
10-16 11:13:00.060 13775 13775 E AndroidRuntime: 	at com.c.a.c.a(RxPermissionsFragment.java:63)
10-16 11:13:00.060 13775 13775 E AndroidRuntime: 	at com.c.a.c.onRequestPermissionsResult(RxPermissionsFragment.java:49)
10-16 11:13:00.060 13775 13775 E AndroidRuntime: 	at android.app.Activity.dispatchRequestPermissionsResultToFragment(Activity.java:7638)
10-16 11:13:00.060 13775 13775 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:7482)
10-16 11:13:00.060 13775 13775 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4462)

**Comment by BarretWu** [comment]
same error

**Comment by lambui09** [comment]
Same error
