### ISSUE TITLE
0.10.2版本 出现 ANR

### ISSUE THREAD

**Issue by liuruimilk** [tbruyelle/RxPermissions#304]
日志如下,操作流程就是进入APP闪屏页请求了Manifest.permission.WRITE_EXTERNAL_STORAGE, Manifest.permission.READ_PHONE_STATE这两权限,弹框都点了同意....然后就一直卡着了,subscribe啥回调都没有,onError也不会走,然后如果你点击屏幕,就会报ANR....

"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x757ac050 self=0xeb3c4000
  | sysTid=5384 nice=-10 cgrp=default sched=0/0 handle=0xefb62494
  | state=S schedstat=( 3978900516 56020841 1045 ) utm=369 stm=28 core=3 HZ=100
  | stack=0xff043000-0xff045000 stackSize=8MB
  | held mutexes=
  kernel: (couldn't read /proc/self/task/5384/stack stderr:Permission denied)
  native: #00 pc 00019f04  /system/lib/libc.so (syscall+28)
  native: #01 pc 0001db3d  /system/lib/libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*)+88)
  native: #02 pc 00066755  /system/lib/libc.so (NonPI::MutexLockWithTimeout(pthread_mutex_internal_t*, bool, timespec const*)+436)
  native: #03 pc 000619f3  /system/lib/libc.so (fwrite+38)
  native: #04 pc 0146e0bf  /preas/app/WebViewGoogle/WebViewGoogle.apk (offset 4948000) (???)
  at org.chromium.base.library_loader.LibraryLoader.nativeLibraryLoaded(Native method)
  at org.chromium.base.library_loader.LibraryLoader.c(PG:100)
  at org.chromium.base.library_loader.LibraryLoader.a(PG:11)
  - locked <0x068b11bd> (a java.lang.Object)
  at ku.c(PG:28)
  at ky.run(PG:3)
  - locked <0x0dcc53b2> (a java.lang.Object)
  at org.chromium.base.task.TaskRunnerImpl.d_(PG:50)
  at EQ.run(unavailable:-1)
  at android.os.Handler.handleCallback(Handler.java:907)
  at android.os.Handler.dispatchMessage(Handler.java:105)
  at android.os.Looper.loop(Looper.java:216)
  at android.app.ActivityThread.main(ActivityThread.java:7625)
  at java.lang.reflect.Method.invoke(Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by liuruimilk** [comment]
对了,不是必现.....但是频率也不低

**Comment by everyline** [comment]
是的，有几率出现
