### ISSUE TITLE
got exception and than crash

### ISSUE THREAD

**Issue by dreamhb** [tbruyelle/RxPermissions#63]
at rx.internal.util.ScalarSynchronousObservable.create(ScalarSynchronousObservable.java:68)
at rx.Observable.just(Observable.java:1575)                                                 
at com.tbruyelle.rxpermissions.RxPermissions.request(RxPermissions.java:125)

**Comment by dreamhb** [comment]
on Android 4.2.2

**Comment by tarasantoshchuk** [comment]
@dreamhb can you provide full stacktrace with exception name?
or at least part of it, above "at com.tbruyelle.rxpermissions.RxPermissions..."

**Comment by dreamhb** [comment]
It is the multidex problem, which cause rxjava exception, not this project, thanks for your work!
The problem is described here: https://github.com/square/retrofit/issues/1628
