### ISSUE TITLE
java.lang.RuntimeException: Failure delivering result ResultInfo

### ISSUE THREAD

**Issue by Gregliest** [tbruyelle/RxPermissions#89]
It says in the readme that "the request must be done during an initialization phase."  Otherwise, "the user's answer will never be emitted to the subscriber."  For my application, it doesn't matter if some of the responses are dropped, so I'm experimenting with dispatching the permissions request from a non reactive event.  However, I'm getting the exception thrown [here](https://github.com/tbruyelle/RxPermissions/blob/master/lib/src/main/java/com/tbruyelle/rxpermissions/RxPermissions.java#L291) 

Here's the stack trace:

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=42, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.takescoop.android.dogfood/com.tbruyelle.rxpermissions.ShadowActivity}: java.lang.IllegalStateException: RxPermissions.onRequestPermissionsResult invoked but didn't find the corresponding permission request.
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
        at android.app.ActivityThread.-wrap16(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
        Caused by: java.lang.IllegalStateException: RxPermissions.onRequestPermissionsResult invoked but didn't find the corresponding permission request.
        at com.tbruyelle.rxpermissions.RxPermissions.onRequestPermissionsResult(RxPermissions.java:291)
        at com.tbruyelle.rxpermissions.ShadowActivity.onRequestPermissionsResult(ShadowActivity.java:38)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:6582)
        at android.app.Activity.dispatchActivityResult(Activity.java:6460)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742) 
        at android.app.ActivityThread.-wrap16(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

Is there a workaround?  Much appreciated!

**Comment by tbruyelle** [comment]
You can also have this kind of exception if you don't follow the library guidelines.

**Comment by Gregliest** [comment]
Thanks for the quick response.  Yes, I'm going off the rails a little bit here.  As I said, I don't care if some of the responses get dropped if the activity gets recreated.  Also, I'm triggering the permissions request from an event, and  I can't easily make the element reactive.  I ran into this exception as I was experimenting with how RxPermissions would handle the permissions request in this case.  

I read through https://github.com/tbruyelle/RxPermissions/issues/3, and I think that the tradeoff of flexibility (requiring the permissions request in the initialization) for completeness is perfectly reasonable, for cases where you need to guarantee that the result is emitted to the subscriber.  However, it would also seem reasonable for the library to support cases where it doesn't matter if the occasional request gets dropped.  At least, I didn't expect the library to crash.  I also have no way to catch the exception and act on it, since it's thrown completely internally to the library.  Is there a way to emit the error to the observable?

**Comment by tbruyelle** [comment]
We can't emit an error precisely because we can't find the subject for the requested permission.

**Comment by tarasantoshchuk** [comment]
@Gregliest 
can you post some code, where you're requesting permissions?
we might be able to provide workaround for you

**Comment by Gregliest** [comment]
I'm requesting permissions inside of an `OnClickListener` inside of a Dialog.  The code itself is pretty generic, let me know if you actually want to see it.  I'm testing by setting the developer option "Don't keep activities", triggering the system permissions dialog, exiting the app, re-entering the app, and then clicking "allow".  

I did a little more digging, since the system permissions dialog is popping up twice.  The first dialog is attached to the old observable from the destroyed activity, and the second dialog must be spawned when the `ShadowActivity` gets recreated.  The app crashes when I click allow on the second dialog.

**Comment by tbruyelle** [comment]
Your code seems to gather all conditions to trigger the biggest flaw of this library : configuration change handling. As you read in #3 there's no workaround, so we have the choice to follow the guidelines or to stop using `RxPermissions`.

**Comment by epool** [comment]
@Gregliest you could try `0.9.0` to verify if that version fixes you problem.
