### ISSUE TITLE
Failure delivering result ResultInfo when requesting location permission in Fragment.onCreateView

### ISSUE THREAD

**Issue by matejhacin** [tbruyelle/RxPermissions#94]
I have this block of code inside Fragment.onCreateView

    `RxPermissions.getInstance(getContext())
                .request(
                        Manifest.permission.ACCESS_FINE_LOCATION,
                        Manifest.permission.ACCESS_COARSE_LOCATION)
                .subscribe(new Action1<Boolean>() {
                    @Override
                    public void call(Boolean granted) {
                        mapFragment.setHasLocationPermission(granted);
                        listFragment.setHasLocationPermission(granted);

                        // Set up ViewPager with Adapter
                        ACFragmentPagerAdapter fragmentPagerAdapter = new ACFragmentPagerAdapter(getChildFragmentManager());
                        fragmentPagerAdapter.addFragment(mapFragment, getContext().getResources().getString(R.string.main_pager_tab_map));
                        fragmentPagerAdapter.addFragment(listFragment, getContext().getResources().getString(R.string.locations));
                        viewPager.setAdapter(fragmentPagerAdapter);

                        // Tabs
                        tabLayout.setupWithViewPager(viewPager);
                    }
                });`

I often get a crash like this:

> Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=42, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.avantcar.a2go/com.tbruyelle.rxpermissions.ShadowActivity}: rx.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3884)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3927)
       at android.app.ActivityThread.-wrap16(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1514)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5683)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
Caused by rx.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
       at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:374)
       at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:371)
       at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
       at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
       at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
       at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:204)
       at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:503)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:461)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:244)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:145)
       at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:74)
       at rx.internal.operators.OperatorBufferWithSize$BufferExact.onNext(OperatorBufferWithSize.java:114)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:391)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:353)
       at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:838)
       at rx.observers.SerializedObserver.onNext(SerializedObserver.java:95)
       at rx.observers.SerializedSubscriber.onNext(SerializedSubscriber.java:95)
       at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.innerNext(OnSubscribeConcatMap.java:182)
       at rx.internal.operators.OnSubscribeConcatMap$ConcatMapInnerSubscriber.onNext(OnSubscribeConcatMap.java:335)
       at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onNext(SubjectSubscriptionManager.java:223)
       at rx.subjects.PublishSubject.onNext(PublishSubject.java:114)
       at com.tbruyelle.rxpermissions.RxPermissions.onRequestPermissionsResult(RxPermissions.java:290)
       at com.tbruyelle.rxpermissions.ShadowActivity.onRequestPermissionsResult(ShadowActivity.java:32)
       at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:6586)
       at android.app.Activity.dispatchActivityResult(Activity.java:6465)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3880)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3927)
       at android.app.ActivityThread.-wrap16(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1514)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5683)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
       at com.avantcar.a2go.fragments.ACMainLocationsFragment$1.call(ACMainLocationsFragment.java:106)
       at com.avantcar.a2go.fragments.ACMainLocationsFragment$1.call(ACMainLocationsFragment.java:98)
       at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
       at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:503)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:461)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:244)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:145)
       at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:74)
       at rx.internal.operators.OperatorBufferWithSize$BufferExact.onNext(OperatorBufferWithSize.java:114)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:391)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:353)
       at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:838)
       at rx.observers.SerializedObserver.onNext(SerializedObserver.java:95)
       at rx.observers.SerializedSubscriber.onNext(SerializedSubscriber.java:95)
       at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.innerNext(OnSubscribeConcatMap.java:182)
       at rx.internal.operators.OnSubscribeConcatMap$ConcatMapInnerSubscriber.onNext(OnSubscribeConcatMap.java:335)
       at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onNext(SubjectSubscriptionManager.java:223)
       at rx.subjects.PublishSubject.onNext(PublishSubject.java:114)
       at com.tbruyelle.rxpermissions.RxPermissions.onRequestPermissionsResult(RxPermissions.java:290)
       at com.tbruyelle.rxpermissions.ShadowActivity.onRequestPermissionsResult(ShadowActivity.java:32)
       at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:6586)
       at android.app.Activity.dispatchActivityResult(Activity.java:6465)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3880)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3927)
       at android.app.ActivityThread.-wrap16(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1514)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5683)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)

Do you know what could be causing this and how can I fix it? Thanks!
Love the library by the way. Keep up the good work!

**Comment by tbruyelle** [comment]
It seems to be something linked to your fragment usage, not RxPermissions.

**Comment by epool** [comment]
I totally agree with @tbruyelle . But @matejhacin you could try the latest `0.9.0` version.

**Comment by tbruyelle** [comment]
Closed no feedback from op

**Comment by selmanon** [comment]
**OnErrorNotImplementedException**
This indicates that an Observable tried to call its observer’s onError() method, but that no such method existed. You can eliminate this by either fixing the Observable so that it no longer reaches an error condition, by implementing an onError handler in the observer, or by intercepting the onError notification before it reaches the observer by using one of the operators described elsewhere on this page.
